# Generated by Django 5.2.1 on 2025-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('standard', models.IntegerField()),
                ('af', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
